name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o git-webhook-receiver-linux app/main/main.go

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o git-webhook-receiver-darwin app/main/main.go

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.tag_version.outputs.version }}
          body: |
            Description of the release.

      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./git-webhook-receiver-linux
          asset_name: git-webhook-receiver-linux
          asset_content_type: application/octet-stream

      - name: Upload macOS Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./git-webhook-receiver-darwin
          asset_name: git-webhook-receiver-darwin
          asset_content_type: application/octet-stream
